import { Inter } from "next/font/google";
import { NavLink } from "ui";
import "./globals.css";
import { cn } from "lib/utils";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "p-8")}>
        <header>
          <nav>
            <ul className="flex gap-4 list-none">
              <li>
                <NavLink href="/">Home</NavLink>
              </li>
              <li>
                <NavLink href="/serverless-rendering">
                  Serverless rendering
                </NavLink>
              </li>
            </ul>
          </nav>
        </header>
        <div className="py-4"></div>
        <main>{children}</main>
      </body>
    </html>
  );
}
